### ISSUE TITLE
embed code improvement

### ISSUE THREAD

**Issue by ocformula** [MagicTeaMC/Orange-Dog#28]
![2023-12-20 05 01 27에 스크린샷 찍기](https://github.com/MagicTeaMC/Orange-Dog/assets/105538842/262c3659-7ca4-435f-9dd2-8266b2806133)
What about improving the message and embed styles when using the play command?
Perhaps the code of commands like playnext could be written similarly.

**Comment by MagicTeaMC** [comment]
sounds great 😃

**Comment by ocformula** [comment]
https://github.com/ocformula/Orange-Dog/tree/develop
Can you tell me what needs to be improved on my commit (localization, etc.)?

**Comment by MagicTeaMC** [comment]
i dont have time to test it, but i think you can delete some unused codes, and anything is fine 🙂

**Comment by MagicTeaMC** [comment]
#30
